import React, { useState } from "react";
import { Linking, Pressable, Text } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Card, Field, Loading, Message, PrimaryButton, Row, Screen, SecondaryButton, day, ui } from "../../components/PassengerScreen";
import { tr } from "../../core/i18n";
import { passengerServicesApi } from "../../core/passenger-api";
import { useSession } from "../../core/session-store";
import { useMessages } from "../../core/use-messages";
import type { RootStackParamList } from "../../navigation/types";
const back=(n:{goBack:()=>void})=>n.goBack;
export function AccountProfileScreen({navigation}:NativeStackScreenProps<RootStackParamList,"Profile">){const {messages}=useMessages(), profile=useSession(s=>s.profile),restore=useSession(s=>s.restore);const [name,setName]=useState(profile?.name??"");const save=useMutation({mutationFn:()=>passengerServicesApi.updateProfile({name:name.trim()}),onSuccess:()=>restore()});return <Screen title={tr(messages,"profile.title")} onBack={back(navigation)}><Field value={name} onChangeText={setName} label={tr(messages,"profile.name")}/><Card><Row title={tr(messages,"profile.phone")} value={profile?.phone}/><Row title={tr(messages,"profile.email")} value={profile?.email}/></Card>{save.isError?<Message danger>{tr(messages,"common.error")}</Message>:null}<PrimaryButton label={tr(messages,"common.save")} disabled={!name.trim()||save.isPending} onPress={()=>save.mutate()}/></Screen>}
export function SupportScreen({navigation}:NativeStackScreenProps<RootStackParamList,"Support">){const {messages}=useMessages();const client=useQueryClient();const [subject,setSubject]=useState(""),[body,setBody]=useState("");const q=useQuery({queryKey:["support-tickets"],queryFn:passengerServicesApi.tickets});const create=useMutation({mutationFn:()=>passengerServicesApi.createTicket(subject.trim(),body.trim()),onSuccess:async()=>{setSubject("");setBody("");await client.invalidateQueries({queryKey:["support-tickets"]})}});return <Screen title={tr(messages,"support.title")} onBack={back(navigation)}><Field value={subject} onChangeText={setSubject} label={tr(messages,"support.subject")}/><Field value={body} onChangeText={setBody} multiline label={tr(messages,"support.message")}/><PrimaryButton label={tr(messages,"support.send")} disabled={!subject.trim()||!body.trim()||create.isPending} onPress={()=>create.mutate()}/><Text style={ui.section}>{tr(messages,"support.myTickets")}</Text>{q.isPending?<Loading/>:q.data?.items.length?q.data.items.map(x=><Card key={x.id} onPress={()=>navigation.navigate("SupportTicket",{ticketId:x.id})}><Row title={x.subject} subtitle={day(x.updatedAt)} value={tr(messages,`support.status.${x.status}`)}/></Card>):<Message>{tr(messages,"support.empty")}</Message>}</Screen>}
export function SupportTicketScreen({navigation,route}:NativeStackScreenProps<RootStackParamList,"SupportTicket">){const {messages}=useMessages();const client=useQueryClient();const [body,setBody]=useState("");const q=useQuery({queryKey:["support-ticket",route.params.ticketId],queryFn:()=>passengerServicesApi.ticket(route.params.ticketId)});const reply=useMutation({mutationFn:()=>passengerServicesApi.replyTicket(route.params.ticketId,body.trim()),onSuccess:async()=>{setBody("");await client.invalidateQueries({queryKey:["support-ticket",route.params.ticketId]})}});return <Screen title={tr(messages,"support.details")} onBack={back(navigation)}>{q.isPending?<Loading/>:q.data?<><Card><Text style={ui.h2}>{q.data.subject}</Text>{q.data.messages?.map(m=><Card key={m.id}><Text style={ui.paragraph}>{m.body}</Text><Text style={ui.caption}>{day(m.createdAt)}</Text></Card>)}</Card><Field value={body} onChangeText={setBody} multiline label={tr(messages,"support.reply")}/><PrimaryButton label={tr(messages,"support.send")} disabled={!body.trim()||reply.isPending} onPress={()=>reply.mutate()}/></>:<Message danger>{tr(messages,"common.error")}</Message>}</Screen>}
export function LegalScreen({navigation}:NativeStackScreenProps<RootStackParamList,"Legal">){const {locale,messages}=useMessages();const q=useQuery({queryKey:["legal",locale],queryFn:()=>passengerServicesApi.legal(locale)});return <Screen title={tr(messages,"legal.title")} onBack={back(navigation)}>{q.isPending?<Loading/>:q.data?.map(d=><Card key={d.id} onPress={()=>navigation.navigate("LegalDocument",{document:d})}><Row title={d.title} subtitle={d.summary??undefined}/></Card>)}</Screen>}
export function LegalDocumentScreen({navigation,route}:NativeStackScreenProps<RootStackParamList,"LegalDocument">){const {messages}=useMessages();const client=useQueryClient();const consent=useQuery({queryKey:["legal-consent"],queryFn:passengerServicesApi.legalConsent,enabled:route.params.document.requiresAcceptance});const pending=consent.data?.pending.some(x=>x.id===route.params.document.id&&x.version===route.params.document.version)??false;const accept=useMutation({mutationFn:()=>passengerServicesApi.acceptLegal(route.params.document.id,route.params.document.version),onSuccess:()=>client.invalidateQueries({queryKey:["legal-consent"]})});return <Screen title={route.params.document.title} onBack={back(navigation)}><Card><Text style={ui.paragraph}>{route.params.document.body}</Text></Card><Text style={ui.caption}>{tr(messages,"legal.version")} {route.params.document.version}</Text>{route.params.document.requiresAcceptance&&consent.isPending?<Loading/>:pending?<PrimaryButton label={tr(messages,"legal.accept")} disabled={accept.isPending} onPress={()=>accept.mutate()}/>:route.params.document.requiresAcceptance?<Message>{tr(messages,"legal.accepted")}</Message>:null}{accept.isError?<Message danger>{tr(messages,"common.error")}</Message>:null}</Screen>}
function ConfigPage({navigation,kind}:{navigation:{goBack:()=>void};kind:"about"|"contact"}){const {messages}=useMessages();const q=useQuery({queryKey:["passenger-config"],queryFn:passengerServicesApi.config});const setting=q.data?.settings[`passenger.${kind}`] as {titleKey?:string;bodyKey?:string;phone?:string;email?:string;website?:string}|undefined;return <Screen title={tr(messages,`${kind}.title`)} onBack={back(navigation)}>{q.isPending?<Loading/>:setting?<Card>{setting.titleKey?<Text style={ui.h2}>{tr(messages,setting.titleKey)}</Text>:null}{setting.bodyKey?<Text style={ui.paragraph}>{tr(messages,setting.bodyKey)}</Text>:null}{setting.phone?<Row title={tr(messages,"contact.phone")} value={setting.phone} onPress={()=>void Linking.openURL(`tel:${setting.phone}`)}/>:null}{setting.email?<Row title={tr(messages,"contact.email")} value={setting.email} onPress={()=>void Linking.openURL(`mailto:${setting.email}`)}/>:null}{setting.website?<Row title={tr(messages,"contact.website")} value={setting.website} onPress={()=>void Linking.openURL(setting.website!)}/>:null}</Card>:<Message>{tr(messages,"common.unavailable")}</Message>}</Screen>}
export const AboutScreen=({navigation}:NativeStackScreenProps<RootStackParamList,"About">)=><ConfigPage navigation={navigation} kind="about"/>;export const ContactScreen=({navigation}:NativeStackScreenProps<RootStackParamList,"Contact">)=><ConfigPage navigation={navigation} kind="contact"/>;
export function SettingsScreen({navigation}:NativeStackScreenProps<RootStackParamList,"Settings">){const {messages}=useMessages();const profile=useSession(s=>s.profile),restore=useSession(s=>s.restore);const q=useQuery({queryKey:["passenger-config"],queryFn:passengerServicesApi.config});const locales=q.data?.settings["passenger.localization"]?.supportedLocales??[];const setLocale=useMutation({mutationFn:(locale:"ar"|"fr"|"en")=>passengerServicesApi.updateProfile({locale}),onSuccess:()=>restore()});return <Screen title={tr(messages,"settings.title")} onBack={back(navigation)}><Text style={ui.section}>{tr(messages,"settings.language")}</Text>{locales.map(locale=><Pressable key={locale} style={[ui.chip,locale===profile?.locale&&ui.chipActive]} onPress={()=>setLocale.mutate(locale)}><Text style={[ui.chipText,locale===profile?.locale&&ui.chipTextActive]}>{tr(messages,`language.${locale}`)}</Text></Pressable>)}</Screen>}
export function DeleteAccountScreen({navigation}:NativeStackScreenProps<RootStackParamList,"DeleteAccount">){const {messages}=useMessages();const logout=useSession(s=>s.logout);const config=useQuery({queryKey:["passenger-config"],queryFn:passengerServicesApi.config});const current=useQuery({queryKey:["deletion-request"],queryFn:passengerServicesApi.deletionRequest});const [confirmation,setConfirmation]=useState(""),[reason,setReason]=useState("");const required=config.data?.settings["passenger.accountDeletion"]?.confirmationText??"";const request=useMutation({mutationFn:()=>passengerServicesApi.requestDeletion(confirmation,reason.trim()||undefined),onSuccess:()=>logout()});const cancel=useMutation({mutationFn:passengerServicesApi.cancelDeletion,onSuccess:()=>current.refetch()});return <Screen title={tr(messages,"accountDeletion.title")} onBack={back(navigation)}>{current.data?<Card><Text style={ui.warning}>{tr(messages,"accountDeletion.pending")}</Text><Row title={tr(messages,"accountDeletion.scheduledFor")} value={day(current.data.scheduledFor)}/><SecondaryButton label={tr(messages,"accountDeletion.cancel")} onPress={()=>cancel.mutate()}/></Card>:<><Message danger>{tr(messages,"accountDeletion.warning")}</Message>{required?<Message>{required}</Message>:null}<Field value={reason} onChangeText={setReason} multiline label={tr(messages,"accountDeletion.reason")}/><Field value={confirmation} onChangeText={setConfirmation} label={tr(messages,"accountDeletion.confirmation")}/><PrimaryButton destructive label={tr(messages,"accountDeletion.submit")} disabled={!required||confirmation!==required||request.isPending} onPress={()=>request.mutate()}/></>}</Screen>}
