import React, { useState } from "react";
import { Share, Text } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Card, Field, Loading, Message, PrimaryButton, Row, Screen, SecondaryButton, day, money, useUi } from "../../components/PassengerScreen";
import { tr } from "../../core/i18n";
import { passengerServicesApi } from "../../core/passenger-api";
import { useMessages } from "../../core/use-messages";
import type { RootStackParamList } from "../../navigation/types";
const back = (navigation: { goBack: () => void }) => navigation.goBack;
export function ReferralsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, "Referrals">) { const { messages}= useMessages(), ui = useUi(); const [code,setCode]=useState(""); const client=useQueryClient(); const own=useQuery({queryKey:["referral-code"],queryFn:passengerServicesApi.referralCode}); const list=useQuery({queryKey:["referrals"],queryFn:passengerServicesApi.referrals}); const apply=useMutation({mutationFn:()=>passengerServicesApi.applyReferral(code.trim()),onSuccess:()=>client.invalidateQueries({queryKey:["referrals"]})}); return <Screen title={tr(messages,"referrals.title")} onBack={back(navigation)}>{own.isPending?<Loading/>:own.data?<Card><Text style={ui.heroValue}>{own.data.code}</Text><Text style={ui.heroLabel}>{tr(messages,"referrals.myCode")}</Text><SecondaryButton label={tr(messages,"referrals.share")} onPress={()=>void Share.share({message:own.data!.code})}/></Card>:null}<Field value={code} onChangeText={setCode} label={tr(messages,"referrals.enterCode")}/><PrimaryButton label={tr(messages,"referrals.apply")} disabled={code.trim().length<4||apply.isPending} onPress={()=>apply.mutate()}/>{apply.isError?<Message danger>{tr(messages,"common.error")}</Message>:null}<Text style={ui.section}>{tr(messages,"referrals.history")}</Text>{list.data?.items.map(x=><Card key={x.id}><Row title={x.code} value={tr(messages,`referrals.status.${x.status}`)}/></Card>)}</Screen>; }
export function SubscriptionsScreen({ navigation }: NativeStackScreenProps<RootStackParamList, "Subscriptions">) { const { messages}= useMessages(), ui = useUi(); const client=useQueryClient(); const plans=useQuery({queryKey:["subscription-plans"],queryFn:passengerServicesApi.plans}); const active=useQuery({queryKey:["subscription"],queryFn:passengerServicesApi.subscription}); const refresh=()=>client.invalidateQueries({queryKey:["subscription"]}); const subscribe=useMutation({mutationFn:passengerServicesApi.subscribe,onSuccess:refresh}); const cancel=useMutation({mutationFn:passengerServicesApi.cancelSubscription,onSuccess:refresh}); return <Screen title={tr(messages,"subscriptions.title")} onBack={back(navigation)}>{active.data?<Card><Text style={ui.h2}>{active.data.plan?.name}</Text><Row title={tr(messages,"subscriptions.status")} value={tr(messages,`subscriptions.status.${active.data.status}`)}/><Row title={tr(messages,"subscriptions.renewal")} value={active.data.autoRenew?tr(messages,"common.enabled"):tr(messages,"common.disabled")}/>{active.data.autoRenew?<SecondaryButton label={tr(messages,"subscriptions.cancelRenewal")} onPress={()=>cancel.mutate(active.data?.id)}/>:null}</Card>:null}{plans.isPending?<Loading/>:plans.data?.map(p=><Card key={p.id}><Text style={ui.h2}>{p.name}</Text>{p.description?<Text style={ui.paragraph}>{p.description}</Text>:null}<Row title={tr(messages,"subscriptions.price")} value={money(p.price,p.currency)}/><PrimaryButton label={tr(messages,"subscriptions.subscribe")} disabled={!!active.data||subscribe.isPending} onPress={()=>subscribe.mutate(p.id)}/></Card>)}</Screen>; }
